enum ScreenNames {
  Home = "Home",
  Settings = "Setting",
  Welcome = "Welcome",
  Login = "Login",
  Register = "Register",
  Landing = "Landing",
  Forgot = "Forgot",
  Main = "Main",
  Notification = "Notification",
  Profile = "Profile",
  Community = "Community",
  Medical = "Medical",
  Setting = "Setting",
  VerificationPassword = "VerificationPassword",
  Terms = "Terms",
  Policy = "Policy",
  About = "About",
  Faq = "Faq",
  History = "History",
  Report = "Report",
  Library = "Library",
  Symptom = "Symptom",
  Medication = "Medication",
  Booking = "Booking",
  ChooseUserScreen = "ChooseUserScreen",
  GatherProfileFirstScreen = "GatherProfileFirstScreen",
  GatherProfileSecondScreen = "GatherProfileSecondScreen",
  RedefinePasswordScreen = "RedefinePasswordScreen",
  BookSinglePageScreen = "BookSinglePageScreen",
  PostSingleScreen = "PostSingleScreen",
  ArticleScreen = "ArticleScreen",
  CreateMedicationScreen = "CreateMedicationScreen",
  CreateSymptomScreen = "CreateSymptomScreen",
  CreateApppoinmentScreen = "CreateAppointmentScreen",
  AskReplyScreen = "AskReplyScreen",
  DailyScreen = "DailyScreen",
  AdminMainScreen = "AdminMainScreen",
  AnalisesScreen = "AnalisesScreen",
  AutorizationScreen =  "AutorizationScreen",
  MainMedicoScreen =  "MainMedicoScreen",
  MyPostsScreen = "MyPostsScreen",
  OptionsAdmincreen = "OptionsAdmincreen",
  SinglePostsScreen = "SinglePostsScreen",
  TipsMedicoScreen = "TipsMedicoScreen",
  QuestionScreen = "QuestionScreen",
  ProfileAdminScreen = 'ProfileAdminScreen',
  GatherDoctorProfileFirstScreen = 'GatherDoctorProfileFirstScreen',
  MyTipsScreen = 'MyTipsScreen',
  SuggestVideoScreen = 'SuggestVideoScreen',
  ProfileMedicoScreen = 'ProfileMedicoScreen',
}

export default ScreenNames;



