enum ScreenNames {
  Home = "Home",
  Settings = "Setting",
  Welcome = "Welcome",
  Login = "Login",
  Register = "Register",
  Landing = "Landing",
  Forgot = "Forgot",
  Main = "Main",
  Notification = "Notification",
  Profile = "Profile",
  Community = "Community",
  Medical = "Medical",
  Setting = "Setting",
  VerificationPassword = "VerificationPassword",
  Terms = "Terms",
  Policy = "Policy",
  About = "About",
  Faq = "Faq",
  History = "History",
  Report = "Report",
  Library = "Library",
  Symptom = "Symptom",
  Medication = "Medication",
  Booking = "Booking",
  ChooseUserScreen = "ChooseUserScreen",
  GatherProfileFirstScreen = "GatherProfileFirstScreen",
  GatherProfileSecondScreen = "GatherProfileSecondScreen",
  RedefinePasswordScreen = "RedefinePasswordScreen",
  BookSinglePageScreen = "BookSinglePageScreen",
  PostSingleScreen = "PostSingleScreen",
  ArticleScreen = "ArticleScreen",
  CreateMedicationScreen = "CreateMedicationScreen",
  CreateSymptomScreen = "CreateSymptomScreen",
  CreateApppoinmentScreen = "CreateAppointmentScreen",
}

export default ScreenNames;



